const { getConnection } = require('./db');

// Definición de todas las tablas del Sistema de Gestión de Aeropuerto (SGA)
const TABLAS_SCHEMA = {
  // ===== TABLAS DE CATÁLOGO Y ESTADOS =====
  SGA_PAIS: `
    CREATE TABLE SGA_PAIS (
      PA_ID_PAIS NUMBER PRIMARY KEY,
      PA_NOMBRE VARCHAR2(100) NOT NULL,
      PA_CODIGO VARCHAR2(3) UNIQUE NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_CIUDAD: `
    CREATE TABLE SGA_CIUDAD (
      CD_ID_CIUDAD NUMBER PRIMARY KEY,
      CD_NOMBRE VARCHAR2(100) NOT NULL,
      PA_ID_PAIS NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (PA_ID_PAIS) REFERENCES SGA_PAIS(PA_ID_PAIS)
    )
  `,

  SGA_ESTADO_AEROPUERTO: `
    CREATE TABLE SGA_ESTADO_AEROPUERTO (
      EAP_ID_ESTADO_AEROPUERTO NUMBER PRIMARY KEY,
      EAP_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_AEROLINEA: `
    CREATE TABLE SGA_ESTADO_AEROLINEA (
      EAL_ID_ESTADO_AEROLINEA NUMBER PRIMARY KEY,
      EAL_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_AVION: `
    CREATE TABLE SGA_ESTADO_AVION (
      EAV_ID_ESTADO_AVION NUMBER PRIMARY KEY,
      EAV_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_VUELO: `
    CREATE TABLE SGA_ESTADO_VUELO (
      ESV_ID_ESTADO_VUELO NUMBER PRIMARY KEY,
      ESV_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TIPO_VUELO: `
    CREATE TABLE SGA_TIPO_VUELO (
      ID_TIPO_VUELO NUMBER PRIMARY KEY,
      TV_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_DIA: `
    CREATE TABLE SGA_DIA (
      DIA_ID_DIA NUMBER PRIMARY KEY,
      DIA_NOMBRE VARCHAR2(20) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_CLASE_BOLETO: `
    CREATE TABLE SGA_CLASE_BOLETO (
      CLB_ID_CLASE_BOLETO NUMBER PRIMARY KEY,
      CLB_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TIPO_EQUIPAJE: `
    CREATE TABLE SGA_TIPO_EQUIPAJE (
      TEQ_ID NUMBER PRIMARY KEY,
      TEQ_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TIPO_UBICACION: `
    CREATE TABLE SGA_TIPO_UBICACION (
      TUB_ID NUMBER PRIMARY KEY,
      TUB_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_OBJETO: `
    CREATE TABLE SGA_ESTADO_OBJETO (
      EOB_ID_ESTADO_OBJETO NUMBER PRIMARY KEY,
      EOB_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_MOTIVO: `
    CREATE TABLE SGA_MOTIVO (
      MOT_ID_MOTIVO NUMBER PRIMARY KEY,
      MOT_DESCRIPCION VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_PUESTO: `
    CREATE TABLE SGA_PUESTO (
      PTS_ID_PUESTO NUMBER PRIMARY KEY,
      PTS_NOMBRE VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_DEPARTAMENTO: `
    CREATE TABLE SGA_DEPARTAMENTO (
      DEP_ID NUMBER PRIMARY KEY,
      DEP_NOMBRE VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_EMPLEADO: `
    CREATE TABLE SGA_ESTADO_EMPLEADO (
      ESE_ID_ESTADO_EMPLEADO NUMBER PRIMARY KEY,
      ESE_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TERMINAL: `
    CREATE TABLE SGA_TERMINAL (
      TRM_ID_TERMINAL NUMBER PRIMARY KEY,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      TRM_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_TERMINAL_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO)
    )
  `,

  SGA_TURNO: `
    CREATE TABLE SGA_TURNO (
      TRN_ID NUMBER PRIMARY KEY,
      TRN_NOMBRE VARCHAR2(50) NOT NULL,
      TRN_HORA_INICIO TIMESTAMP NOT NULL,
      TRN_HORA_FIN TIMESTAMP NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_METODO_PAGO: `
    CREATE TABLE SGA_METODO_PAGO (
      MPG_ID NUMBER PRIMARY KEY,
      MPG_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_REEMBOLSO: `
    CREATE TABLE SGA_ESTADO_REEMBOLSO (
      ESR_ID NUMBER PRIMARY KEY,
      ESR_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_ABORDAJE: `
    CREATE TABLE SGA_ESTADO_ABORDAJE (
      EAB_ID_ESTADO_ABORDAJE NUMBER PRIMARY KEY,
      EAB_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_CHECKIN: `
    CREATE TABLE SGA_ESTADO_CHECKIN (
      ECK_ID_ESTADO NUMBER PRIMARY KEY,
      ECK_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_ASIENTO: `
    CREATE TABLE SGA_ESTADO_ASIENTO (
      EAS_ID_ESTADO NUMBER PRIMARY KEY,
      EAS_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ROL: `
    CREATE TABLE SGA_ROL (
      ROL_ID_ROL NUMBER PRIMARY KEY,
      ROL_NOMBRE VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_PERMISO: `
    CREATE TABLE SGA_PERMISO (
      PER_ID_PERMISO NUMBER PRIMARY KEY,
      PER_NOMBRE VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ROL_TRIPULACION: `
    CREATE TABLE SGA_ROL_TRIPULACION (
      RTC_ID_ROL_TRIPULACION NUMBER PRIMARY KEY,
      RTC_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TIPO_OPERACION_PISTA: `
    CREATE TABLE SGA_TIPO_OPERACION_PISTA (
      TOP_ID_OPERACION_PISTA NUMBER PRIMARY KEY,
      TOP_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_TIPO_EVENTO: `
    CREATE TABLE SGA_TIPO_EVENTO (
      TE_ID NUMBER PRIMARY KEY,
      TE_DESCRIPCION VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_ASIGNACION: `
    CREATE TABLE SGA_ESTADO_ASIGNACION (
      EAS_ID_ESTADO_ASIGNACION NUMBER PRIMARY KEY,  
      EAS_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_ESTADO_RESERVA: `
    CREATE TABLE SGA_ESTADO_RESERVA (
      ESR_ID NUMBER PRIMARY KEY,
      ESR_DESCRIPCION VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  // ===== TABLAS PRINCIPALES =====
  SGA_AEROPUERTO: `
    CREATE TABLE SGA_AEROPUERTO (
      APT_ID_AEROPUERTO NUMBER PRIMARY KEY,
      APT_CODIGO VARCHAR2(10) UNIQUE NOT NULL,
      APT_NOMBRE VARCHAR2(100) NOT NULL,
      APT_ID_CIUDAD NUMBER NOT NULL,
      EAP_ID_ESTADO_AEROPUERTO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_AEROPUERTO_CIUDAD FOREIGN KEY (APT_ID_CIUDAD) REFERENCES SGA_CIUDAD(CD_ID_CIUDAD),
      CONSTRAINT FK_AEROPUERTO_ESTADO FOREIGN KEY (EAP_ID_ESTADO_AEROPUERTO) REFERENCES SGA_ESTADO_AEROPUERTO(EAP_ID_ESTADO_AEROPUERTO)
    )
  `,

  SGA_AEROLINEA: `
    CREATE TABLE SGA_AEROLINEA (
      ARL_ID_AEROLINEA NUMBER PRIMARY KEY,
      ARL_NOMBRE VARCHAR2(100) NOT NULL,
      ARL_CODIGO_IATA VARCHAR2(3) UNIQUE NOT NULL,
      EAL_ID_ESTADO_AEROLINEA NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_AEROLINEA_ESTADO FOREIGN KEY (EAL_ID_ESTADO_AEROLINEA) REFERENCES SGA_ESTADO_AEROLINEA(EAL_ID_ESTADO_AEROLINEA)
    )
  `,

  SGA_MODELO_AVION: `
    CREATE TABLE SGA_MODELO_AVION (
      MDA_ID_MODELO NUMBER PRIMARY KEY,
      MDA_NOMBRE_MODELO VARCHAR2(100) NOT NULL,
      MDA_CAPACIDAD_PASAJEROS NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE
    )
  `,

  SGA_AVION: `
    CREATE TABLE SGA_AVION (
      AVN_ID_AVION NUMBER PRIMARY KEY,
      MDA_ID_MODELO NUMBER NOT NULL,
      AVN_MATRICULA VARCHAR2(20) UNIQUE NOT NULL,
      EAV_ID_ESTADO_AVION NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_AVION_MODELO FOREIGN KEY (MDA_ID_MODELO) REFERENCES SGA_MODELO_AVION(MDA_ID_MODELO),
      CONSTRAINT FK_AVION_ESTADO FOREIGN KEY (EAV_ID_ESTADO_AVION) REFERENCES SGA_ESTADO_AVION(EAV_ID_ESTADO_AVION)
    )
  `,

  SGA_PROGRAMA_VUELO: `
    CREATE TABLE SGA_PROGRAMA_VUELO (
      PRV_ID_PROGRAMA NUMBER PRIMARY KEY,
      PRV_NUMERO_VUELO VARCHAR2(10) NOT NULL,
      ARL_ID_AEROLINEA NUMBER NOT NULL,
      ID_AEROPUERTO_ORIGEN NUMBER NOT NULL,
      ID_AEROPUERTO_DESTINO NUMBER NOT NULL,
      ID_TIPO_VUELO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PROGRAMA_AEROLINEA FOREIGN KEY (ARL_ID_AEROLINEA) REFERENCES SGA_AEROLINEA(ARL_ID_AEROLINEA),
      CONSTRAINT FK_PROGRAMA_ORIGEN FOREIGN KEY (ID_AEROPUERTO_ORIGEN) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO),
      CONSTRAINT FK_PROGRAMA_DESTINO FOREIGN KEY (ID_AEROPUERTO_DESTINO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO),
      CONSTRAINT FK_PROGRAMA_TIPO FOREIGN KEY (ID_TIPO_VUELO) REFERENCES SGA_TIPO_VUELO(ID_TIPO_VUELO)
    )
  `,

  SGA_DIA_PROGRAMA_VUELO: `
    CREATE TABLE SGA_DIA_PROGRAMA_VUELO (
      DPV_ID_DIA_PROGRAMA NUMBER PRIMARY KEY,
      PRV_ID_PROGRAMA NUMBER NOT NULL,
      DIA_ID_DIA NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_DIA_PROGRAMA_VUELO FOREIGN KEY (PRV_ID_PROGRAMA) REFERENCES SGA_PROGRAMA_VUELO(PRV_ID_PROGRAMA),
      CONSTRAINT FK_DIA_PROGRAMA_DIA FOREIGN KEY (DIA_ID_DIA) REFERENCES SGA_DIA(DIA_ID_DIA)
    )
  `,

  SGA_VUELO: `
    CREATE TABLE SGA_VUELO (
      VL_ID_VUELO NUMBER PRIMARY KEY,
      PRV_ID_PROGRAMA NUMBER NOT NULL,
      VL_FECHA DATE NOT NULL,
      AVN_ID_AVION NUMBER NOT NULL,
      VL_PLAZAS_VACIAS NUMBER DEFAULT 0,
      ESV_ID_ESTADO_VUELO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_VUELO_PROGRAMA FOREIGN KEY (PRV_ID_PROGRAMA) REFERENCES SGA_PROGRAMA_VUELO(PRV_ID_PROGRAMA),
      CONSTRAINT FK_VUELO_AVION FOREIGN KEY (AVN_ID_AVION) REFERENCES SGA_AVION(AVN_ID_AVION),
      CONSTRAINT FK_VUELO_ESTADO FOREIGN KEY (ESV_ID_ESTADO_VUELO) REFERENCES SGA_ESTADO_VUELO(ESV_ID_ESTADO_VUELO)
    )
  `,

  SGA_ESCALA_TECNICA: `
    CREATE TABLE SGA_ESCALA_TECNICA (
      ET_ID_ESCALA NUMBER PRIMARY KEY,
      VL_ID_VUELO NUMBER NOT NULL,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      ET_NUMERO_ORDEN NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ESCALA_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ESCALA_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO)
    )
  `,

  SGA_PASAJERO: `
    CREATE TABLE SGA_PASAJERO (
      PAS_ID_PASAJERO NUMBER PRIMARY KEY,
      PAS_PRIMER_NOMBRE VARCHAR2(50) NOT NULL,
      PAS_SEGUNDO_NOMBRE VARCHAR2(50),
      PAS_TERCER_NOMBRE VARCHAR2(50),
      PAS_PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
      PAS_SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL,
      PAS_PASAPORTE VARCHAR2(20) UNIQUE NOT NULL,
      PAS_FECHA_NACIMIENTO DATE NOT NULL,
      PA_ID_PAIS NUMBER NOT NULL,
      PAS_TELEFONO VARCHAR2(20),
      PAS_EMAIL VARCHAR2(100),
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PASAJERO_PAIS FOREIGN KEY (PA_ID_PAIS) REFERENCES SGA_PAIS(PA_ID_PAIS)
    )
  `,

  SGA_PUERTA_EMBARQUE: `
    CREATE TABLE SGA_PUERTA_EMBARQUE (
      PTE_ID_PUERTA NUMBER PRIMARY KEY,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      TRM_ID_TERMINAL NUMBER NOT NULL,
      PTE_NUMERO_PUERTA VARCHAR2(10) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PUERTA_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO),
      CONSTRAINT FK_PUERTA_TERMINAL FOREIGN KEY (TRM_ID_TERMINAL) REFERENCES SGA_TERMINAL(TRM_ID_TERMINAL),
      CONSTRAINT UQ_PUERTA_AEROPUERTO UNIQUE (APT_ID_AEROPUERTO, PTE_NUMERO_PUERTA)
    )
  `,

  SGA_EMPLEADO: `
    CREATE TABLE SGA_EMPLEADO (
      EMP_ID_EMPLEADO NUMBER PRIMARY KEY,
      EMP_PRIMER_NOMBRE VARCHAR2(50) NOT NULL,
      EMP_SEGUNDO_NOMBRE VARCHAR2(50),
      EMP_TERCER_NOMBRE VARCHAR2(50),
      EMP_PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
      EMP_SEGUNDO_APELLIDO VARCHAR2(50) NOT NULL,
      PTS_ID_PUESTO NUMBER NOT NULL,
      DEP_ID NUMBER NOT NULL,
      ESE_ID_ESTADO_EMPLEADO NUMBER NOT NULL,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_EMPLEADO_PUESTO FOREIGN KEY (PTS_ID_PUESTO) REFERENCES SGA_PUESTO(PTS_ID_PUESTO),
      CONSTRAINT FK_EMPLEADO_DEPARTAMENTO FOREIGN KEY (DEP_ID) REFERENCES SGA_DEPARTAMENTO(DEP_ID),
      CONSTRAINT FK_EMPLEADO_ESTADO FOREIGN KEY (ESE_ID_ESTADO_EMPLEADO) REFERENCES SGA_ESTADO_EMPLEADO(ESE_ID_ESTADO_EMPLEADO),
      CONSTRAINT FK_EMPLEADO_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO)
    )
  `,

  SGA_RESERVA: `
    CREATE TABLE SGA_RESERVA (
      REV_ID_RESERVA NUMBER PRIMARY KEY,
      PAS_ID_PASAJERO NUMBER NOT NULL,
      ESR_ID NUMBER NOT NULL,
      REV_FECHA DATE DEFAULT SYSDATE,
      REV_PRECIO NUMBER(10,2) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_RESERVA_PASAJERO FOREIGN KEY (PAS_ID_PASAJERO) REFERENCES SGA_PASAJERO(PAS_ID_PASAJERO),
      CONSTRAINT FK_RESERVA_ESTADO FOREIGN KEY (ESR_ID) REFERENCES SGA_ESTADO_RESERVA(ESR_ID)
    )
  `,

  SGA_DETALLE: `
    CREATE TABLE SGA_DETALLE (
      DTR_ID_DETALLE NUMBER PRIMARY KEY,
      REV_ID_RESERVA NUMBER NOT NULL,
      VL_ID_VUELO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_DETALLE_RESERVA FOREIGN KEY (REV_ID_RESERVA) REFERENCES SGA_RESERVA(REV_ID_RESERVA),
      CONSTRAINT FK_DETALLE_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO)
    )
  `,

  SGA_BOLETO: `
    CREATE TABLE SGA_BOLETO (
      BLT_ID_BOLETO NUMBER PRIMARY KEY,
      REV_ID_RESERVA NUMBER NOT NULL,
      CLB_ID_CLASE_BOLETO NUMBER NOT NULL,
      BLT_PRECIO NUMBER(10,2) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_BOLETO_RESERVA FOREIGN KEY (REV_ID_RESERVA) REFERENCES SGA_RESERVA(REV_ID_RESERVA),
      CONSTRAINT FK_BOLETO_CLASE FOREIGN KEY (CLB_ID_CLASE_BOLETO) REFERENCES SGA_CLASE_BOLETO(CLB_ID_CLASE_BOLETO)
    )
  `,

  SGA_EQUIPAJE: `
    CREATE TABLE SGA_EQUIPAJE (
      EQP_EQUIPAJE NUMBER PRIMARY KEY,
      BLT_ID_BOLETO NUMBER NOT NULL,
      TEQ_ID NUMBER NOT NULL,
      EQP_PESO NUMBER(5,2) NOT NULL,
      EQP_DESCRIPCION VARCHAR2(200),
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_EQUIPAJE_BOLETO FOREIGN KEY (BLT_ID_BOLETO) REFERENCES SGA_BOLETO(BLT_ID_BOLETO),
      CONSTRAINT FK_EQUIPAJE_TIPO FOREIGN KEY (TEQ_ID) REFERENCES SGA_TIPO_EQUIPAJE(TEQ_ID)
    )
  `,

  SGA_ASIGNACION_PUERTA: `
    CREATE TABLE SGA_ASIGNACION_PUERTA (
      ASP_ID_ASIGNACION NUMBER PRIMARY KEY,
      VL_ID_VUELO NUMBER NOT NULL,
      PTE_ID_PUERTA NUMBER NOT NULL,
      ASP_FECHA DATE NOT NULL,
      ASP_HORA_INICIO TIMESTAMP,
      ASP_HORA_FIN TIMESTAMP,
      EAS_ID_ESTADO_ASIGNACION NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ASIGNACION_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ASIGNACION_PUERTA FOREIGN KEY (PTE_ID_PUERTA) REFERENCES SGA_PUERTA_EMBARQUE(PTE_ID_PUERTA),
      CONSTRAINT FK_ASIGNACION_ESTADO FOREIGN KEY (EAS_ID_ESTADO_ASIGNACION) REFERENCES SGA_ESTADO_ASIGNACION(EAS_ID_ESTADO_ASIGNACION)
    )
  `,

  SGA_HISTORIAL_VUELO: `
    CREATE TABLE SGA_HISTORIAL_VUELO (
      HVL_ID_HISTORIAL NUMBER PRIMARY KEY,
      VL_ID_VUELO NUMBER NOT NULL,
      TE_ID NUMBER NOT NULL,
      ESV_ESTADO_PREVIO NUMBER,
      ESV_ESTADO_ACTUAL NUMBER,
      HVL_DESCRIPCION VARCHAR2(500),
      HVL_FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_HISTORIAL_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_HISTORIAL_EVENTO FOREIGN KEY (TE_ID) REFERENCES SGA_TIPO_EVENTO(TE_ID),
      CONSTRAINT FK_HISTORIAL_EST_PREV FOREIGN KEY (ESV_ESTADO_PREVIO) REFERENCES SGA_ESTADO_VUELO(ESV_ID_ESTADO_VUELO),
      CONSTRAINT FK_HISTORIAL_EST_ACT FOREIGN KEY (ESV_ESTADO_ACTUAL) REFERENCES SGA_ESTADO_VUELO(ESV_ID_ESTADO_VUELO)
    )
  `,

  SGA_OBJETO_PERDIDO: `
    CREATE TABLE SGA_OBJETO_PERDIDO (
      OBP_ID_OBJETO NUMBER PRIMARY KEY,
      OBP_DESCRIPCION VARCHAR2(200) NOT NULL,
      OBP_FECHA_REPORTE DATE DEFAULT SYSDATE,
      TUB_ID NUMBER NOT NULL,
      EOB_ID_ESTADO_OBJETO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER,
      ARL_ID_AEROLINEA NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_OBJETO_UBICACION FOREIGN KEY (TUB_ID) REFERENCES SGA_TIPO_UBICACION(TUB_ID),
      CONSTRAINT FK_OBJETO_ESTADO FOREIGN KEY (EOB_ID_ESTADO_OBJETO) REFERENCES SGA_ESTADO_OBJETO(EOB_ID_ESTADO_OBJETO),
      CONSTRAINT FK_OBJETO_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_OBJETO_AEROLINEA FOREIGN KEY (ARL_ID_AEROLINEA) REFERENCES SGA_AEROLINEA(ARL_ID_AEROLINEA)
    )
  `,

  SGA_ARRESTO: `
    CREATE TABLE SGA_ARRESTO (
      ARS_ID_ARRESTO NUMBER PRIMARY KEY,
      PAS_ID_PASAJERO NUMBER NOT NULL,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER,
      MOT_ID_MOTIVO NUMBER NOT NULL,
      ARS_FECHA DATE DEFAULT SYSDATE,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ARRESTO_PASAJERO FOREIGN KEY (PAS_ID_PASAJERO) REFERENCES SGA_PASAJERO(PAS_ID_PASAJERO),
      CONSTRAINT FK_ARRESTO_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO),
      CONSTRAINT FK_ARRESTO_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ARRESTO_MOTIVO FOREIGN KEY (MOT_ID_MOTIVO) REFERENCES SGA_MOTIVO(MOT_ID_MOTIVO)
    )
  `,

  // ===== NUEVAS TABLAS PRINCIPALES =====
  SGA_ASIGNACION_EMPLEADO: `
    CREATE TABLE SGA_ASIGNACION_EMPLEADO (
      ASE_ID NUMBER PRIMARY KEY,
      EMP_ID_EMPLEADO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER,
      PTE_ID_PUERTA NUMBER,
      TRN_ID NUMBER NOT NULL,
      ASE_FECHA DATE NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ASIG_EMP_EMPLEADO FOREIGN KEY (EMP_ID_EMPLEADO) REFERENCES SGA_EMPLEADO(EMP_ID_EMPLEADO),
      CONSTRAINT FK_ASIG_EMP_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ASIG_EMP_PUERTA FOREIGN KEY (PTE_ID_PUERTA) REFERENCES SGA_PUERTA_EMBARQUE(PTE_ID_PUERTA),
      CONSTRAINT FK_ASIG_EMP_TURNO FOREIGN KEY (TRN_ID) REFERENCES SGA_TURNO(TRN_ID)
    )
  `,

  SGA_PAGO: `
    CREATE TABLE SGA_PAGO (
      PAG_ID NUMBER PRIMARY KEY,
      REV_ID_RESERVA NUMBER NOT NULL,
      MPG_ID NUMBER NOT NULL,
      PAG_MONTO NUMBER(10,2) NOT NULL,
      PAG_FECHA DATE DEFAULT SYSDATE,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PAGO_RESERVA FOREIGN KEY (REV_ID_RESERVA) REFERENCES SGA_RESERVA(REV_ID_RESERVA),
      CONSTRAINT FK_PAGO_METODO FOREIGN KEY (MPG_ID) REFERENCES SGA_METODO_PAGO(MPG_ID)
    )
  `,

  SGA_REEMBOLSO: `
    CREATE TABLE SGA_REEMBOLSO (
      REM_ID NUMBER PRIMARY KEY,
      PAG_ID NUMBER NOT NULL,
      REM_MONTO NUMBER(10,2) NOT NULL,
      REM_FECHA DATE DEFAULT SYSDATE,
      REM_MOTIVO VARCHAR2(500),
      ESR_ID NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_REEMBOLSO_PAGO FOREIGN KEY (PAG_ID) REFERENCES SGA_PAGO(PAG_ID),
      CONSTRAINT FK_REEMBOLSO_ESTADO FOREIGN KEY (ESR_ID) REFERENCES SGA_ESTADO_REEMBOLSO(ESR_ID)
    )
  `,

  SGA_PASAJERO_VUELO: `
    CREATE TABLE SGA_PASAJERO_VUELO (
      ID_PASAJERO_VUELO NUMBER PRIMARY KEY,
      PAS_ID_PASAJERO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER NOT NULL,
      EAB_ID_ESTADO_ABORDAJE NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PAS_VUELO_PASAJERO FOREIGN KEY (PAS_ID_PASAJERO) REFERENCES SGA_PASAJERO(PAS_ID_PASAJERO),
      CONSTRAINT FK_PAS_VUELO_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_PAS_VUELO_ABORDAJE FOREIGN KEY (EAB_ID_ESTADO_ABORDAJE) REFERENCES SGA_ESTADO_ABORDAJE(EAB_ID_ESTADO_ABORDAJE)
    )
  `,

  SGA_CHECKIN: `
    CREATE TABLE SGA_CHECKIN (
      CHK_ID NUMBER PRIMARY KEY,
      PAS_ID_PASAJERO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER NOT NULL,
      CHK_FECHA_CHECKIN DATE DEFAULT SYSDATE,
      ECK_ID_ESTADO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_CHECKIN_PASAJERO FOREIGN KEY (PAS_ID_PASAJERO) REFERENCES SGA_PASAJERO(PAS_ID_PASAJERO),
      CONSTRAINT FK_CHECKIN_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_CHECKIN_ESTADO FOREIGN KEY (ECK_ID_ESTADO) REFERENCES SGA_ESTADO_CHECKIN(ECK_ID_ESTADO)
    )
  `,

  SGA_ASIENTO: `
    CREATE TABLE SGA_ASIENTO (
      ASI_ID_ASIENTO NUMBER PRIMARY KEY,
      AVN_ID_AVION NUMBER NOT NULL,
      ASI_NUMERO VARCHAR2(5) NOT NULL,
      CLB_ID_CLASE_BOLETO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ASIENTO_AVION FOREIGN KEY (AVN_ID_AVION) REFERENCES SGA_AVION(AVN_ID_AVION),
      CONSTRAINT FK_ASIENTO_CLASE FOREIGN KEY (CLB_ID_CLASE_BOLETO) REFERENCES SGA_CLASE_BOLETO(CLB_ID_CLASE_BOLETO),
      CONSTRAINT UQ_ASIENTO_AVION UNIQUE (AVN_ID_AVION, ASI_NUMERO)
    )
  `,

  SGA_ASIGNACION_ASIENTO: `
    CREATE TABLE SGA_ASIGNACION_ASIENTO (
      ASA_ID_ASIGNACION NUMBER PRIMARY KEY,
      BLT_ID_BOLETO NUMBER NOT NULL,
      ASI_ID_ASIENTO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER NOT NULL,
      EAS_ID_ESTADO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ASIG_ASIENTO_BOLETO FOREIGN KEY (BLT_ID_BOLETO) REFERENCES SGA_BOLETO(BLT_ID_BOLETO),
      CONSTRAINT FK_ASIG_ASIENTO_ASIENTO FOREIGN KEY (ASI_ID_ASIENTO) REFERENCES SGA_ASIENTO(ASI_ID_ASIENTO),
      CONSTRAINT FK_ASIG_ASIENTO_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ASIG_ASIENTO_ESTADO FOREIGN KEY (EAS_ID_ESTADO) REFERENCES SGA_ESTADO_ASIENTO(EAS_ID_ESTADO)
    )
  `,

  SGA_USUARIO: `
    CREATE TABLE SGA_USUARIO (
      USR_ID_USUARIO NUMBER PRIMARY KEY,
      USR_USERNAME VARCHAR2(50) UNIQUE NOT NULL,
      USR_PASSWORD VARCHAR2(255) NOT NULL,
      EMP_ID_EMPLEADO NUMBER NOT NULL,
      ROL_ID_ROL NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (EMP_ID_EMPLEADO) REFERENCES SGA_EMPLEADO(EMP_ID_EMPLEADO),
      CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID_ROL) REFERENCES SGA_ROL(ROL_ID_ROL)
    )
  `,

  SGA_ROL_PERMISO: `
    CREATE TABLE SGA_ROL_PERMISO (
      ROL_ID_ROL NUMBER NOT NULL,
      PER_ID_PERMISO NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      PRIMARY KEY (ROL_ID_ROL, PER_ID_PERMISO),
      CONSTRAINT FK_ROL_PERM_ROL FOREIGN KEY (ROL_ID_ROL) REFERENCES SGA_ROL(ROL_ID_ROL),
      CONSTRAINT FK_ROL_PERM_PERMISO FOREIGN KEY (PER_ID_PERMISO) REFERENCES SGA_PERMISO(PER_ID_PERMISO)
    )
  `,

  SGA_MANTENIMIENTO_AVION: `
    CREATE TABLE SGA_MANTENIMIENTO_AVION (
      MAV_ID NUMBER PRIMARY KEY,
      AVN_ID_AVION NUMBER NOT NULL,
      EMP_ID_EMPLEADO NUMBER NOT NULL,
      MAV_FECHA_INICIO DATE NOT NULL,
      MAV_FECHA_FIN DATE,
      MAV_DESCRIPCION VARCHAR2(500),
      MAV_TIPO VARCHAR2(100) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_MANT_AVION_AVION FOREIGN KEY (AVN_ID_AVION) REFERENCES SGA_AVION(AVN_ID_AVION),
      CONSTRAINT FK_MANT_AVION_EMP FOREIGN KEY (EMP_ID_EMPLEADO) REFERENCES SGA_EMPLEADO(EMP_ID_EMPLEADO)
    )
  `,

  SGA_TRIPULACION_VUELO: `
    CREATE TABLE SGA_TRIPULACION_VUELO (
      TRV_ID_TRIPULACION NUMBER PRIMARY KEY,
      EMP_ID_EMPLEADO NUMBER NOT NULL,
      VL_ID_VUELO NUMBER NOT NULL,
      RTC_ID_ROL_TRIPULACION NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_TRIP_VUELO_EMP FOREIGN KEY (EMP_ID_EMPLEADO) REFERENCES SGA_EMPLEADO(EMP_ID_EMPLEADO),
      CONSTRAINT FK_TRIP_VUELO_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_TRIP_VUELO_ROL FOREIGN KEY (RTC_ID_ROL_TRIPULACION) REFERENCES SGA_ROL_TRIPULACION(RTC_ID_ROL_TRIPULACION),
      CONSTRAINT UQ_EMPLEADO_VUELO UNIQUE (EMP_ID_EMPLEADO, VL_ID_VUELO)
    )
  `,

  SGA_PISTA: `
    CREATE TABLE SGA_PISTA (
      PIS_ID_PISTA NUMBER PRIMARY KEY,
      APT_ID_AEROPUERTO NUMBER NOT NULL,
      PIS_NOMBRE VARCHAR2(50) NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_PISTA_AEROPUERTO FOREIGN KEY (APT_ID_AEROPUERTO) REFERENCES SGA_AEROPUERTO(APT_ID_AEROPUERTO)
    )
  `,

  SGA_ASIGNACION_PISTA: `
    CREATE TABLE SGA_ASIGNACION_PISTA (
      ASP_ID_ASIGNACION_PISTA NUMBER PRIMARY KEY,
      VL_ID_VUELO NUMBER NOT NULL,
      PIS_ID_PISTA NUMBER NOT NULL,
      ASP_FECHA DATE NOT NULL,
      TOP_ID_OPERACION_PISTA NUMBER NOT NULL,
      DELETED NUMBER(1) DEFAULT 0 NOT NULL,
      FECHA_ELIMINACION DATE,
      CONSTRAINT FK_ASIG_PISTA_VUELO FOREIGN KEY (VL_ID_VUELO) REFERENCES SGA_VUELO(VL_ID_VUELO),
      CONSTRAINT FK_ASIG_PISTA_PISTA FOREIGN KEY (PIS_ID_PISTA) REFERENCES SGA_PISTA(PIS_ID_PISTA),
      CONSTRAINT FK_ASIG_PISTA_OPER FOREIGN KEY (TOP_ID_OPERACION_PISTA) REFERENCES SGA_TIPO_OPERACION_PISTA(TOP_ID_OPERACION_PISTA)
    )
  `
};

// Datos de ejemplo para poblar las tablas
const DATOS_INICIALES = {
  SGA_PAIS: [
    "INSERT INTO SGA_PAIS VALUES (1, 'Guatemala', 'GT')",
    "INSERT INTO SGA_PAIS VALUES (2, 'Estados Unidos', 'US')",
    "INSERT INTO SGA_PAIS VALUES (3, 'México', 'MX')",
    "INSERT INTO SGA_PAIS VALUES (4, 'Colombia', 'CO')"
  ],
  
  SGA_CIUDAD: [
    "INSERT INTO SGA_CIUDAD VALUES (1, 'Guatemala City', 1)",
    "INSERT INTO SGA_CIUDAD VALUES (2, 'Miami', 2)",
    "INSERT INTO SGA_CIUDAD VALUES (3, 'Ciudad de México', 3)",
    "INSERT INTO SGA_CIUDAD VALUES (4, 'Los Ángeles', 2)",
    "INSERT INTO SGA_CIUDAD VALUES (5, 'Bogotá', 4)"
  ],

  SGA_ESTADO_AEROPUERTO: [
    "INSERT INTO SGA_ESTADO_AEROPUERTO VALUES (1, 'ACTIVO')",
    "INSERT INTO SGA_ESTADO_AEROPUERTO VALUES (2, 'MANTENIMIENTO')",
    "INSERT INTO SGA_ESTADO_AEROPUERTO VALUES (3, 'CERRADO')"
  ],

  SGA_ESTADO_AEROLINEA: [
    "INSERT INTO SGA_ESTADO_AEROLINEA VALUES (1, 'ACTIVA')",
    "INSERT INTO SGA_ESTADO_AEROLINEA VALUES (2, 'SUSPENDIDA')",
    "INSERT INTO SGA_ESTADO_AEROLINEA VALUES (3, 'INACTIVA')"
  ],

  SGA_ESTADO_AVION: [
    "INSERT INTO SGA_ESTADO_AVION VALUES (1, 'OPERATIVO')",
    "INSERT INTO SGA_ESTADO_AVION VALUES (2, 'MANTENIMIENTO')",
    "INSERT INTO SGA_ESTADO_AVION VALUES (3, 'FUERA_DE_SERVICIO')"
  ],

  SGA_ESTADO_VUELO: [
    "INSERT INTO SGA_ESTADO_VUELO VALUES (1, 'PROGRAMADO')",
    "INSERT INTO SGA_ESTADO_VUELO VALUES (2, 'RETRASADO')",
    "INSERT INTO SGA_ESTADO_VUELO VALUES (3, 'EN_VUELO')",
    "INSERT INTO SGA_ESTADO_VUELO VALUES (4, 'ATERRIZANDO')",
    "INSERT INTO SGA_ESTADO_VUELO VALUES (5, 'COMPLETADO')",
    "INSERT INTO SGA_ESTADO_VUELO VALUES (6, 'CANCELADO')"
  ],

  SGA_TIPO_VUELO: [
    "INSERT INTO SGA_TIPO_VUELO VALUES (1, 'NACIONAL')",
    "INSERT INTO SGA_TIPO_VUELO VALUES (2, 'INTERNACIONAL')",
    "INSERT INTO SGA_TIPO_VUELO VALUES (3, 'CHARTER')"
  ],

  SGA_DIA: [
    "INSERT INTO SGA_DIA VALUES (1, 'LUNES')",
    "INSERT INTO SGA_DIA VALUES (2, 'MARTES')",
    "INSERT INTO SGA_DIA VALUES (3, 'MIERCOLES')",
    "INSERT INTO SGA_DIA VALUES (4, 'JUEVES')",
    "INSERT INTO SGA_DIA VALUES (5, 'VIERNES')",
    "INSERT INTO SGA_DIA VALUES (6, 'SABADO')",
    "INSERT INTO SGA_DIA VALUES (7, 'DOMINGO')"
  ],

  SGA_CLASE_BOLETO: [
    "INSERT INTO SGA_CLASE_BOLETO VALUES (1, 'ECONOMICA')",
    "INSERT INTO SGA_CLASE_BOLETO VALUES (2, 'EJECUTIVA')",
    "INSERT INTO SGA_CLASE_BOLETO VALUES (3, 'PRIMERA_CLASE')"
  ],

  SGA_TIPO_EQUIPAJE: [
    "INSERT INTO SGA_TIPO_EQUIPAJE VALUES (1, 'EQUIPAJE_MANO')",
    "INSERT INTO SGA_TIPO_EQUIPAJE VALUES (2, 'EQUIPAJE_BODEGA')",
    "INSERT INTO SGA_TIPO_EQUIPAJE VALUES (3, 'EQUIPAJE_ESPECIAL')"
  ],

  SGA_TIPO_UBICACION: [
    "INSERT INTO SGA_TIPO_UBICACION VALUES (1, 'TERMINAL_A')",
    "INSERT INTO SGA_TIPO_UBICACION VALUES (2, 'TERMINAL_B')",
    "INSERT INTO SGA_TIPO_UBICACION VALUES (3, 'AREA_COMERCIAL')",
    "INSERT INTO SGA_TIPO_UBICACION VALUES (4, 'OFICINAS_PERDIDOS')"
  ],

  SGA_ESTADO_OBJETO: [
    "INSERT INTO SGA_ESTADO_OBJETO VALUES (1, 'REPORTADO')",
    "INSERT INTO SGA_ESTADO_OBJETO VALUES (2, 'EN_CUSTODIA')",
    "INSERT INTO SGA_ESTADO_OBJETO VALUES (3, 'ENTREGADO')",
    "INSERT INTO SGA_ESTADO_OBJETO VALUES (4, 'DESTRUIDO')"
  ],

  SGA_MOTIVO: [
    "INSERT INTO SGA_MOTIVO VALUES (1, 'DOCUMENTOS_FALSOS')",
    "INSERT INTO SGA_MOTIVO VALUES (2, 'COMPORTAMIENTO_AGRESIVO')",
    "INSERT INTO SGA_MOTIVO VALUES (3, 'SUSTANCIAS_PROHIBIDAS')",
    "INSERT INTO SGA_MOTIVO VALUES (4, 'ORDEN_JUDICIAL')"
  ],

  SGA_PUESTO: [
    "INSERT INTO SGA_PUESTO VALUES (1, 'PILOTO')",
    "INSERT INTO SGA_PUESTO VALUES (2, 'COPILOTO')",
    "INSERT INTO SGA_PUESTO VALUES (3, 'AZAFATA')",
    "INSERT INTO SGA_PUESTO VALUES (4, 'CONTROLADOR_AEREO')",
    "INSERT INTO SGA_PUESTO VALUES (5, 'MECANICO')",
    "INSERT INTO SGA_PUESTO VALUES (6, 'SEGURIDAD')"
  ],

  SGA_DEPARTAMENTO: [
    "INSERT INTO SGA_DEPARTAMENTO VALUES (1, 'OPERACIONES')",
    "INSERT INTO SGA_DEPARTAMENTO VALUES (2, 'MANTENIMIENTO')",
    "INSERT INTO SGA_DEPARTAMENTO VALUES (3, 'SEGURIDAD')",
    "INSERT INTO SGA_DEPARTAMENTO VALUES (4, 'ADMINISTRACION')"
  ],

  SGA_ESTADO_EMPLEADO: [
    "INSERT INTO SGA_ESTADO_EMPLEADO VALUES (1, 'ACTIVO')",
    "INSERT INTO SGA_ESTADO_EMPLEADO VALUES (2, 'VACACIONES')",
    "INSERT INTO SGA_ESTADO_EMPLEADO VALUES (3, 'LICENCIA')",
    "INSERT INTO SGA_ESTADO_EMPLEADO VALUES (4, 'INACTIVO')"
  ],

  SGA_TERMINAL: [
    "INSERT INTO SGA_TERMINAL VALUES (1, 'TERMINAL 1')",
    "INSERT INTO SGA_TERMINAL VALUES (2, 'TERMINAL 2')",
    "INSERT INTO SGA_TERMINAL VALUES (3, 'TERMINAL 3')"
  ],

  SGA_TIPO_EVENTO: [
    "INSERT INTO SGA_TIPO_EVENTO VALUES (1, 'PROGRAMACION_VUELO')",
    "INSERT INTO SGA_TIPO_EVENTO VALUES (2, 'CAMBIO_ESTADO')",
    "INSERT INTO SGA_TIPO_EVENTO VALUES (3, 'RETRASO')",
    "INSERT INTO SGA_TIPO_EVENTO VALUES (4, 'CANCELACION')",
    "INSERT INTO SGA_TIPO_EVENTO VALUES (5, 'ASIGNACION_PUERTA')"
  ],

  SGA_ESTADO_ASIGNACION: [
    "INSERT INTO SGA_ESTADO_ASIGNACION VALUES (1, 'ASIGNADA')",
    "INSERT INTO SGA_ESTADO_ASIGNACION VALUES (2, 'EN_USO')",
    "INSERT INTO SGA_ESTADO_ASIGNACION VALUES (3, 'LIBERADA')",
    "INSERT INTO SGA_ESTADO_ASIGNACION VALUES (4, 'CANCELADA')"
  ],

  SGA_ESTADO_RESERVA: [
    "INSERT INTO SGA_ESTADO_RESERVA VALUES (1, 'CONFIRMADA')",
    "INSERT INTO SGA_ESTADO_RESERVA VALUES (2, 'PENDIENTE')",
    "INSERT INTO SGA_ESTADO_RESERVA VALUES (3, 'CANCELADA')",
    "INSERT INTO SGA_ESTADO_RESERVA VALUES (4, 'COMPLETADA')"
  ],

  SGA_AEROPUERTO: [
    "INSERT INTO SGA_AEROPUERTO VALUES (1, 'GUA', 'Aeropuerto Internacional La Aurora', 1, 1)",
    "INSERT INTO SGA_AEROPUERTO VALUES (2, 'MIA', 'Aeropuerto Internacional de Miami', 2, 1)",
    "INSERT INTO SGA_AEROPUERTO VALUES (3, 'MEX', 'Aeropuerto Internacional de la Ciudad de México', 3, 1)",
    "INSERT INTO SGA_AEROPUERTO VALUES (4, 'LAX', 'Aeropuerto Internacional de Los Ángeles', 4, 1)"
  ],

  SGA_AEROLINEA: [
    "INSERT INTO SGA_AEROLINEA VALUES (1, 'TAG Airlines', 'TAG', 1)",
    "INSERT INTO SGA_AEROLINEA VALUES (2, 'Avianca', 'AVA', 1)",
    "INSERT INTO SGA_AEROLINEA VALUES (3, 'Copa Airlines', 'COP', 1)"
  ],

  SGA_MODELO_AVION: [
    "INSERT INTO SGA_MODELO_AVION VALUES (1, 'Boeing 737-800', 189)",
    "INSERT INTO SGA_MODELO_AVION VALUES (2, 'Airbus A320', 180)",
    "INSERT INTO SGA_MODELO_AVION VALUES (3, 'Boeing 787-8', 242)"
  ],

  SGA_AVION: [
    "INSERT INTO SGA_AVION VALUES (1, 1, 'TG-ABC', 1)",
    "INSERT INTO SGA_AVION VALUES (2, 2, 'TG-DEF', 1)",
    "INSERT INTO SGA_AVION VALUES (3, 3, 'HK-XYZ', 1)"
  ],

  // ===== NUEVOS DATOS INICIALES =====
  SGA_TURNO: [
    "INSERT INTO SGA_TURNO VALUES (1, 'MAÑANA', TIMESTAMP '2024-01-01 06:00:00', TIMESTAMP '2024-01-01 14:00:00')",
    "INSERT INTO SGA_TURNO VALUES (2, 'TARDE', TIMESTAMP '2024-01-01 14:00:00', TIMESTAMP '2024-01-01 22:00:00')",
    "INSERT INTO SGA_TURNO VALUES (3, 'NOCHE', TIMESTAMP '2024-01-01 22:00:00', TIMESTAMP '2024-01-02 06:00:00')"
  ],

  SGA_METODO_PAGO: [
    "INSERT INTO SGA_METODO_PAGO VALUES (1, 'TARJETA_CREDITO')",
    "INSERT INTO SGA_METODO_PAGO VALUES (2, 'TARJETA_DEBITO')",
    "INSERT INTO SGA_METODO_PAGO VALUES (3, 'EFECTIVO')",
    "INSERT INTO SGA_METODO_PAGO VALUES (4, 'TRANSFERENCIA')"
  ],

  SGA_ESTADO_REEMBOLSO: [
    "INSERT INTO SGA_ESTADO_REEMBOLSO VALUES (1, 'PENDIENTE')",
    "INSERT INTO SGA_ESTADO_REEMBOLSO VALUES (2, 'APROBADO')",
    "INSERT INTO SGA_ESTADO_REEMBOLSO VALUES (3, 'RECHAZADO')",
    "INSERT INTO SGA_ESTADO_REEMBOLSO VALUES (4, 'PROCESADO')"
  ],

  SGA_ESTADO_ABORDAJE: [
    "INSERT INTO SGA_ESTADO_ABORDAJE VALUES (1, 'ABORDO')",
    "INSERT INTO SGA_ESTADO_ABORDAJE VALUES (2, 'NO_ABORDO')",
    "INSERT INTO SGA_ESTADO_ABORDAJE VALUES (3, 'PENDIENTE')"
  ],

  SGA_ESTADO_CHECKIN: [
    "INSERT INTO SGA_ESTADO_CHECKIN VALUES (1, 'PENDIENTE')",
    "INSERT INTO SGA_ESTADO_CHECKIN VALUES (2, 'REALIZADO')",
    "INSERT INTO SGA_ESTADO_CHECKIN VALUES (3, 'NO_REALIZADO')",
    "INSERT INTO SGA_ESTADO_CHECKIN VALUES (4, 'CANCELADO')"
  ],

  SGA_ESTADO_ASIENTO: [
    "INSERT INTO SGA_ESTADO_ASIENTO VALUES (1, 'ASIGNADO')",
    "INSERT INTO SGA_ESTADO_ASIENTO VALUES (2, 'CAMBIADO')",
    "INSERT INTO SGA_ESTADO_ASIENTO VALUES (3, 'CANCELADO')",
    "INSERT INTO SGA_ESTADO_ASIENTO VALUES (4, 'BLOQUEADO')"
  ],

  SGA_ROL: [
    "INSERT INTO SGA_ROL VALUES (1, 'ADMINISTRADOR')",
    "INSERT INTO SGA_ROL VALUES (2, 'OPERADOR')",
    "INSERT INTO SGA_ROL VALUES (3, 'SUPERVISOR')",
    "INSERT INTO SGA_ROL VALUES (4, 'SEGURIDAD')",
    "INSERT INTO SGA_ROL VALUES (5, 'CHECK_IN')",
    "INSERT INTO SGA_ROL VALUES (6, 'ATENCION_CLIENTE')",
    "INSERT INTO SGA_ROL VALUES (7, 'CONTROL_EQUIPAJE')"
  ],

  SGA_PERMISO: [
    "INSERT INTO SGA_PERMISO VALUES (1, 'GESTION_VUELOS')",
    "INSERT INTO SGA_PERMISO VALUES (2, 'GESTION_PASAJEROS')",
    "INSERT INTO SGA_PERMISO VALUES (3, 'GESTION_CHECKIN')",
    "INSERT INTO SGA_PERMISO VALUES (4, 'GESTION_EQUIPAJE')",
    "INSERT INTO SGA_PERMISO VALUES (5, 'ADMINISTRACION')",
    "INSERT INTO SGA_PERMISO VALUES (6, 'REPORTES')"
  ],

  SGA_ROL_TRIPULACION: [
    "INSERT INTO SGA_ROL_TRIPULACION VALUES (1, 'PILOTO')",
    "INSERT INTO SGA_ROL_TRIPULACION VALUES (2, 'COPILOTO')",
    "INSERT INTO SGA_ROL_TRIPULACION VALUES (3, 'JEFE_CABINA')",
    "INSERT INTO SGA_ROL_TRIPULACION VALUES (4, 'AUXILIAR_VUELO')",
    "INSERT INTO SGA_ROL_TRIPULACION VALUES (5, 'TECNICO_VUELO')"
  ],

  SGA_TIPO_OPERACION_PISTA: [
    "INSERT INTO SGA_TIPO_OPERACION_PISTA VALUES (1, 'DESPEGUE')",
    "INSERT INTO SGA_TIPO_OPERACION_PISTA VALUES (2, 'ATERRIZAJE')"
  ]
};

// Función para verificar si una tabla existe
async function verificarTablaExiste(connection, nombreTabla) {
  try {
    const result = await connection.execute(
      `SELECT COUNT(*) AS EXISTE FROM USER_TABLES WHERE TABLE_NAME = :tabla`,
      [nombreTabla],
      { outFormat: 1 } // OUT_FORMAT_OBJECT
    );
    return result.rows[0].EXISTE > 0;
  } catch (error) {
    return false;
  }
}

// Función para crear una tabla específica
async function crearTabla(connection, nombreTabla, sqlCreacion) {
  try {
    const existe = await verificarTablaExiste(connection, nombreTabla.toUpperCase());
    
    if (existe) {
      console.log(`⚠️  La tabla ${nombreTabla} ya existe, omitiendo...`);
      return { tabla: nombreTabla, estado: 'YA_EXISTE' };
    }

    await connection.execute(sqlCreacion);
    console.log(`✅ Tabla ${nombreTabla} creada exitosamente`);
    return { tabla: nombreTabla, estado: 'CREADA' };
    
  } catch (error) {
    console.log(`❌ Error creando tabla ${nombreTabla}:`, error.message);
    return { tabla: nombreTabla, estado: 'ERROR', error: error.message };
  }
}

// Función para insertar datos iniciales
async function insertarDatosIniciales(connection, nombreTabla, datos) {
  if (!datos || datos.length === 0) return { tabla: nombreTabla, registros: 0 };
  
  let insertados = 0;
  
  for (const sql of datos) {
    try {
      await connection.execute(sql);
      insertados++;
    } catch (error) {
      // Ignorar errores de duplicados y continuar
      if (!error.message.includes('ORA-00001')) {
        console.log(`⚠️  Error insertando en ${nombreTabla}: ${error.message}`);
      }
    }
  }
  
  if (insertados > 0) {
    console.log(`📄 ${insertados} registros insertados en ${nombreTabla}`);
  }
  
  return { tabla: nombreTabla, registros: insertados };
}

// Función principal para inicializar toda la base de datos
async function inicializarBaseDatos(incluirDatos = true) {
  let connection;
  const resultado = {
    tablas_procesadas: [],
    datos_insertados: [],
    errores: [],
    resumen: {}
  };

  try {
    connection = await getConnection();
    console.log('🚀 Iniciando creación completa del Sistema de Gestión de Aeropuerto (SGA)...\n');

    // Crear tablas en orden (respetando dependencias FK)
    const ordenCreacion = [
      // CATÁLOGOS BASE
      'SGA_PAIS', 'SGA_CIUDAD', 
      'SGA_ESTADO_AEROPUERTO', 'SGA_ESTADO_AEROLINEA', 'SGA_ESTADO_AVION', 'SGA_ESTADO_VUELO',
      'SGA_TIPO_VUELO', 'SGA_DIA', 'SGA_CLASE_BOLETO', 'SGA_TIPO_EQUIPAJE', 
      'SGA_TIPO_UBICACION', 'SGA_ESTADO_OBJETO', 'SGA_MOTIVO',
      'SGA_PUESTO', 'SGA_DEPARTAMENTO', 'SGA_ESTADO_EMPLEADO', 
      'SGA_TIPO_EVENTO', 'SGA_ESTADO_ASIGNACION', 'SGA_ESTADO_RESERVA',
      
      // NUEVOS CATÁLOGOS
      'SGA_TURNO', 'SGA_METODO_PAGO', 'SGA_ESTADO_REEMBOLSO', 'SGA_ESTADO_ABORDAJE',
      'SGA_ESTADO_CHECKIN', 'SGA_ESTADO_ASIENTO', 'SGA_ROL', 'SGA_PERMISO',
      'SGA_ROL_TRIPULACION', 'SGA_TIPO_OPERACION_PISTA',
      
      // TABLAS PRINCIPALES (con dependencias)
      'SGA_AEROPUERTO', 'SGA_TERMINAL', 'SGA_AEROLINEA', 'SGA_MODELO_AVION', 'SGA_AVION',
      'SGA_PROGRAMA_VUELO', 'SGA_DIA_PROGRAMA_VUELO', 'SGA_VUELO', 'SGA_ESCALA_TECNICA',
      'SGA_PASAJERO', 'SGA_PUERTA_EMBARQUE', 'SGA_EMPLEADO', 'SGA_PISTA',
      'SGA_RESERVA', 'SGA_DETALLE', 'SGA_BOLETO', 'SGA_EQUIPAJE',
      'SGA_ASIGNACION_PUERTA', 'SGA_HISTORIAL_VUELO', 'SGA_OBJETO_PERDIDO', 'SGA_ARRESTO',
      
      // NUEVAS TABLAS CON DEPENDENCIAS
      'SGA_ASIGNACION_EMPLEADO', 'SGA_PAGO', 'SGA_REEMBOLSO', 'SGA_PASAJERO_VUELO',
      'SGA_CHECKIN', 'SGA_ASIENTO', 'SGA_ASIGNACION_ASIENTO', 'SGA_USUARIO',
      'SGA_ROL_PERMISO', 'SGA_MANTENIMIENTO_AVION', 'SGA_TRIPULACION_VUELO', 
      'SGA_ASIGNACION_PISTA'
    ];
    
    for (const nombreTabla of ordenCreacion) {
      const resultadoTabla = await crearTabla(connection, nombreTabla, TABLAS_SCHEMA[nombreTabla]);
      resultado.tablas_procesadas.push(resultadoTabla);
      
      if (resultadoTabla.estado === 'ERROR') {
        resultado.errores.push(resultadoTabla);
      }
    }

    // Insertar datos iniciales si se solicita
    if (incluirDatos) {
      console.log('\n📊 Insertando datos iniciales del SGA...');
      
      const ordenDatos = [
        'SGA_PAIS', 'SGA_CIUDAD', 
        'SGA_ESTADO_AEROPUERTO', 'SGA_ESTADO_AEROLINEA', 'SGA_ESTADO_AVION', 'SGA_ESTADO_VUELO',
        'SGA_TIPO_VUELO', 'SGA_DIA', 'SGA_CLASE_BOLETO', 'SGA_TIPO_EQUIPAJE', 
        'SGA_TIPO_UBICACION', 'SGA_ESTADO_OBJETO', 'SGA_MOTIVO',
        'SGA_PUESTO', 'SGA_DEPARTAMENTO', 'SGA_ESTADO_EMPLEADO', 'SGA_TERMINAL',
        'SGA_TIPO_EVENTO', 'SGA_ESTADO_ASIGNACION', 'SGA_ESTADO_RESERVA',
        
        // NUEVOS CATÁLOGOS
        'SGA_TURNO', 'SGA_METODO_PAGO', 'SGA_ESTADO_REEMBOLSO', 'SGA_ESTADO_ABORDAJE',
        'SGA_ESTADO_CHECKIN', 'SGA_ESTADO_ASIENTO', 'SGA_ROL', 'SGA_PERMISO',
        'SGA_ROL_TRIPULACION', 'SGA_TIPO_OPERACION_PISTA',
        
        'SGA_AEROPUERTO', 'SGA_AEROLINEA', 'SGA_MODELO_AVION', 'SGA_AVION'
      ];
      
      for (const nombreTabla of ordenDatos) {
        if (DATOS_INICIALES[nombreTabla]) {
          const resultadoDatos = await insertarDatosIniciales(
            connection, 
            nombreTabla, 
            DATOS_INICIALES[nombreTabla]
          );
          resultado.datos_insertados.push(resultadoDatos);
        }
      }
      
      await connection.commit();
      console.log('💾 Datos del SGA guardados exitosamente');
    }

    // Generar resumen
    resultado.resumen = {
      tablas_creadas: resultado.tablas_procesadas.filter(t => t.estado === 'CREADA').length,
      tablas_existentes: resultado.tablas_procesadas.filter(t => t.estado === 'YA_EXISTE').length,
      tablas_con_error: resultado.errores.length,
      total_registros: resultado.datos_insertados.reduce((sum, d) => sum + d.registros, 0)
    };

    console.log('\n🎉 Inicialización del Sistema SGA completada!');
    return resultado;

  } catch (error) {
    console.error('💥 Error fatal en inicialización SGA:', error.message);
    resultado.errores.push({ error_fatal: error.message });
    throw error;
    
  } finally {
    if (connection) {
      try {
        await connection.close();
      } catch (err) {
        console.error('Error cerrando conexión:', err);
      }
    }
  }
}

// Función para eliminar todas las tablas SGA (útil para desarrollo)
async function eliminarTodasLasTablas() {
  let connection;
  try {
    connection = await getConnection();
    console.log('🗑️  Eliminando todas las tablas del SGA...');
    
    // Orden inverso para respetar dependencias FK
    const ordenEliminacion = [
      // ÚLTIMAS TABLAS CON MÁS DEPENDENCIAS
      'SGA_ASIGNACION_PISTA', 'SGA_TRIPULACION_VUELO', 'SGA_MANTENIMIENTO_AVION', 
      'SGA_ROL_PERMISO', 'SGA_USUARIO', 'SGA_ASIGNACION_ASIENTO', 'SGA_ASIENTO',
      'SGA_CHECKIN', 'SGA_PASAJERO_VUELO', 'SGA_REEMBOLSO', 'SGA_PAGO', 'SGA_ASIGNACION_EMPLEADO',
      
      // TABLAS PRINCIPALES
      'SGA_ARRESTO', 'SGA_OBJETO_PERDIDO', 'SGA_HISTORIAL_VUELO', 'SGA_ASIGNACION_PUERTA',
      'SGA_EQUIPAJE', 'SGA_BOLETO', 'SGA_DETALLE', 'SGA_RESERVA', 'SGA_EMPLEADO',
      'SGA_PUERTA_EMBARQUE', 'SGA_PASAJERO', 'SGA_ESCALA_TECNICA', 'SGA_VUELO', 
      'SGA_DIA_PROGRAMA_VUELO', 'SGA_PROGRAMA_VUELO', 'SGA_AVION', 'SGA_MODELO_AVION', 
      'SGA_AEROLINEA', 'SGA_PISTA', 'SGA_TERMINAL', 'SGA_AEROPUERTO', 'SGA_CIUDAD', 'SGA_PAIS',
      
      // CATÁLOGOS
      'SGA_TIPO_OPERACION_PISTA', 'SGA_ROL_TRIPULACION', 'SGA_PERMISO', 'SGA_ROL',
      'SGA_ESTADO_ASIENTO', 'SGA_ESTADO_CHECKIN', 'SGA_ESTADO_ABORDAJE', 'SGA_ESTADO_REEMBOLSO',
      'SGA_METODO_PAGO', 'SGA_TURNO', 'SGA_ESTADO_RESERVA', 'SGA_ESTADO_ASIGNACION', 
      'SGA_TIPO_EVENTO', 'SGA_ESTADO_EMPLEADO', 'SGA_DEPARTAMENTO', 'SGA_PUESTO', 'SGA_MOTIVO', 
      'SGA_ESTADO_OBJETO', 'SGA_TIPO_UBICACION', 'SGA_TIPO_EQUIPAJE', 'SGA_CLASE_BOLETO',
      'SGA_DIA', 'SGA_TIPO_VUELO', 'SGA_ESTADO_VUELO', 'SGA_ESTADO_AVION', 
      'SGA_ESTADO_AEROLINEA', 'SGA_ESTADO_AEROPUERTO'
    ];
    
    for (const tabla of ordenEliminacion) {
      try {
        await connection.execute(`DROP TABLE ${tabla} CASCADE CONSTRAINTS`);
        console.log(`🗑️  Tabla ${tabla} eliminada`);
      } catch (error) {
        if (!error.message.includes('ORA-00942')) {
          console.log(`⚠️  Error eliminando ${tabla}: ${error.message}`);
        }
      }
    }
    
    console.log('✅ Eliminación del SGA completada');
    
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

module.exports = {
  inicializarBaseDatos,
  eliminarTodasLasTablas,
  TABLAS_SCHEMA,
  DATOS_INICIALES
};